### ISSUE TITLE
Bug: All routes are incorrect

### ISSUE THREAD

**Issue by csandman** [dcaraxes/gotenberg-go-client#1]
## Expected Behavior

When I run a conversion from HTML to PDF, the function runs properly

## Current Behavior

The gotenburg docker container returns a 404

## Possible Solution

All routes appear to be incorrect (using the routes for an older version I'd imagine), so just update them. I tried updating the one for HTML conversion from `"/convert/html"` to `"/forms/chromium/convert/html"`, and it's working fine.

## Steps to Reproduce (for bugs)

1. Attempt to run an HTML to PDF conversion against a docker container running the latest version of gotenburg
2. Get a 404

```json
{
  "level": "error",
  "ts": 1715725655.2673457,
  "logger": "api",
  "msg": "code=404, message=Not Found",
  "trace": "e494caa3-2701-47d4-9fae-21c48a5d8ec4",
  "remote_ip": "192.168.65.1",
  "host": "localhost:5454",
  "uri": "/convert/html",
  "method": "GET",
  "path": "/convert/html",
  "referer": "",
  "user_agent": "PostmanRuntime/7.38.0",
  "status": 404,
  "latency": 2335417,
  "latency_human": "2.335417ms",
  "bytes_in": 0,
  "bytes_out": 9
}
```

**Comment by dcaraxes** [comment]
> csandman

Hi! Thanks for the issue! As a temporary solution, you can use the following:

You create a Client and pass it the Hostname on your side, depending on the type of request, which can be viewed here https://gotenberg.dev/docs/routes

For example:
`cl := gotenberg.Client{Hostname: "http://localhost:3001/forms/chromium", httpClient}`

I will try to change all the established routes soon.
