### ISSUE TITLE
Unable to set authorization headers

### ISSUE THREAD

**Issue by IvanWillsBI** [dcaraxes/gotenberg-go-client#6]
Your issue may already be reported!
Please search on the [issue tracker](../../../issues) before creating one.

## Expected Behavior

Some method on a html request that allows setting basic auth to interact with Gotenberg containers that have basic auth
## Current Behavior

Cannot use pdfClient.Store as resp.StatusCode != 200 (401)

## Possible Solution

some sort of
func (r *Request) SetBasicAuth(username, password string) {
	r.Header.Set("Authorization", "Basic "+basicAuth(username, password))
}

## Steps to Reproduce (for bugs)

```
// username := os.Getenv("GOTENBERG_USERNAME")
// password := os.Getenv("GOTENBERG_PASSWORD")

pdfClient := &gotenberg.Client{
    Hostname:   os.Getenv("GOTENBERG_URL"),
    HTTPClient: http.DefaultClient,
}

index, err := gotenberg.NewDocumentFromPath("index.html", htmlFile.Name())
if err != nil {
    return nil, err
}
pdfRequest := gotenberg.NewHTMLRequest(index)
pdfRequest.PaperSize(gotenberg.A4)
pdfRequest.Margins(gotenberg.NoMargins)
pdfRequest.Scale(0.75)
err = pdfClient.Store(pdfRequest, fmt.Sprintf("sage/%s.pdf", purchaseOrderNumber))
if err != nil {
    return nil, err
}
```
For Docker run, the config flag --api-enable-basic-auth: Enable basic authentication - will look for the GOTENBERG_API_BASIC_AUTH_USERNAME and GOTENBERG_API_BASIC_AUTH_PASSWORD environment variables.

When using standard HTTP lib:
```
req.Header.Set("Content-Type", w.FormDataContentType())
req.SetBasicAuth(os.Getenv("GOTENBERG_USERNAME"), os.Getenv("GOTENBERG_PASSWORD"))

```
However, I encountered other issues causing blank PDF generation, which I found the workaround was using this client library. I was able to generate a successful PDF locally using a new docker container 
```
docker run --rm -p 3000:3000 gotenberg/gotenberg:8
```
but our live environment has further config flags set, including --api-enable-basic-auth

## Context

Cannot use Gotenberg client in live environment

## Your Environment

* Version used: Gotenberg 8
* Operating System and version: linux
* Link to your project: n/a

**Comment by dcaraxes** [comment]
Yes, indeed, at the moment the client does not support authorization. I will try to implement it in the coming days, so far this issue will remain open.

**Comment by dcaraxes** [comment]
@IvanWillsBI, I added authorization in version 8.1.4, could you also check the functionality and report the results?

**Comment by dcaraxes** [comment]
@IvanWillsBI I will close this Issue as the tests have shown successful results. If you have problems with authorization, do not hesitate to create a new issue.
